version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    ports:
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password
    volumes:
      - ./mysql:/var/lib/mysql


