version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    ports:
      - "3307:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=reservas
      - MARIADB_DATABASE=reservas
      - MARIADB_PASSWORD=reservas
    volumes:
      - ./mysql:/var/lib/mysql


