version: '2'

services:
  mariadb-usuarios:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      - MARIADB_DATABASE=cliente
      - MARIADB_ROOT_PASSWORD=cliente
    volumes:
      - ./app-usuarios/mysql:/var/lib/mysql

  mariadb-frontend:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      - MARIADB_DATABASE=frontend
      - MARIADB_ROOT_PASSWORD=frontend
    volumes:
      - ./app-clientes/mysql:/var/lib/mysql

  mariadb-productos:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      - MARIADB_DATABASE=productos
      - MARIADB_ROOT_PASSWORD=productos
    volumes:
      - ./app-productos/mysql:/var/lib/mysql

  mariadb-registrodeventas:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      - MARIADB_DATABASE=registrodeventas
      - MARIADB_ROOT_PASSWORD=registrodeventas
    volumes:
      - ./app-registrodeventas/mysql:/var/lib/mysql

  app-productos:
    tty: true
    restart: unless-stopped
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_HOST=mariadb-productos
      - DB_USERNAME=root
      - DB_DATABASE=productos
      - DB_PASSWORD=productos
    depends_on:
      - mariadb-productos
    ports:
      - 3000:3000
    volumes:
      - ./app-productos:/app

  app-registrodeventas:
    tty: true
    restart: unless-stopped
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_HOST=mariadb-registrodeventas
      - DB_USERNAME=root
      - DB_DATABASE=registrodeventas
      - DB_PASSWORD=registrodeventas
      - APP_PRODUCTOS_URL=http://app-productos:3000/api/
      - APP_CLIENTES_URL=http://app-clientes:3000/api/
    depends_on:
      - mariadb-registrodeventas
    ports:
      - 3001:3000
    volumes:
      - ./app-registrodeventas:/app

  app-usuarios:
    tty: true
    restart: unless-stopped
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_HOST=mariadb-usuarios
      - DB_USERNAME=root
      - DB_DATABASE=cliente
      - DB_PASSWORD=cliente
    depends_on:
      - mariadb-usuarios
    ports:
      - 3002:3000
    volumes:
      - ./app-usuarios:/app

  app-frontend:
    tty: true
    restart: unless-stopped
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_HOST=mariadb-frontend
      - DB_USERNAME=root
      - DB_DATABASE=frontend
      - DB_PASSWORD=frontend
      - APP_AUTENTICACION_URL=http://app-autenticacion:3000/api/
      - APP_PRODUCTOS_URL=http://app-productos:3000/api/
      - APP_USUARIOS_URL=http://app-usuarios:3000/api/
      - APP_REGISTRO_URL=http://app-registrodeventas:3000/api/
    ports:
      - 3003:3000
    volumes:
      - ./app-frontend:/app

 